### ISSUE TITLE
Epic: Integrate Vault with Routing to use routing's Parsec.(35-67 days)

### ISSUE THREAD

**Issue by jeanphilippeD** [maidsafe/sn_node#837]
=> Using mock (only if in same process) or real parsec.
  => (could probably run with mock parsec if vault have in same process). Possibly issue if same process but probably exist if multiple process as well.
  
  Tasks:
 - Initial integration with routing Tasks (3-7 days):
    - [x] (1-3 days) (https://github.com/maidsafe/safe_vault/issues/838) First Initial Mock Routing with only the minimum that will be need to be called (`try_next_evt`) does not actually do anything.
    - [x] (2-4 days) (https://github.com/maidsafe/safe_vault/issues/839) Setup the routing instance in `Vault`, probably in `State::Elder`, in the form of `routing::Node`. Make sure Routing is progressing (integration with event loop) (could be just logs). 
      => Is there problem with quic_p2p? probably not since vault is not really using vaults.
      => Command line argument to bootstrap? No, can just setup routing as first node (hard code everything).
    
 - Extend Mock Routing API Tasks(6-13 days):
    - [x] (1-3 days) (https://github.com/maidsafe/safe_vault/issues/840) expose a `vote_for` method to insert payloads into Parsec and new output event to signal consensus about a custom event. (On Vote signale consensus reached) - Make sure it is sensible for routing as well. (No mock_parsec at this stage just pass through)
      => Decide type `Vec<u8>` or enum.
      => The current thinking leans towards accumulating events in routing to keep the API exposed to safe_vault simple.
      => Implement routing EventBox trait with a channel to fit well with current design in Vault. 
      
    - [x] (1-2 weeks)(https://github.com/maidsafe/safe_vault/issues/841) Create continuation scheme to use in all Vault flows.
        - Need to design this early.
        - (5-7 days?) JP: Maybe use existing continuation mechanism to use new Action.
        - (7-10 days?) Maybe need to explore option into more chunk? Might be option.
        - N: Possibly call back or other things.
        
    
 - Extend Routing API Tasks (2-3 days):
   (Probably start with mock routing in vault to make sure we get the right thing).
     - [x] (2-3 days) (https://github.com/maidsafe/safe_vault/issues/868) add a new variant to `NetworkEvent` for custom payloads
       expose a `vote_for` method to insert payloads into Parsec
       add a new output event to signal consensus about a custom event (chain_poll has EventBox so we can just insert it there)
       tests in routing
         - should this event contain just the block payload or proofs as well? (HO 2019-08-29: probably just the payload)
         - that probably applies to chain consensus - the Parsec consensus will just result in passing the event to the chain for accumulation - still unclear whether that is the case, though (HO 2019-08-29)
         - This is probably sending Event through routing EventBox trait (alongside node added events ...)
 - Consume new Routing API in Vault Tasks(15-25 days):
     - [x] (1-3 days) (#875) Currently mock works, make sure the real routing with mock parsec works.
         - Use mock_parsec feature flag? (No access to mock_parsec).
         - maybe routing quic_p2p need to be calle to progress? (Maybe not a problem at the time since only 1 vault.)
         - Maybe debugging because we now using routing to do something.
         - Eventually, but not initially, the routing instance would handle both network and parsec events.

     - [x] (3-5 days) (#872) Modify put and mutation data flows to use Parsec (20 requests in there, handfull of flow modification).
        - The put and mutation flow needs to change so the pay part of the flow goes through only after Parsec consensus (in client-handler) and then in 2.a the remaining flow proceed on all nodes (including data-handler).
        - Implementation details to consider
             - What should be checked before inputting into Parsec? Things like `IData` chunk already existing. (Not really relevant since client still charged). => No
         - Update to test? All should work? Need to wait/run event loop? => with quic_p2p test should already work
         - Maybe would need to create a few Action, probably not need to split function even with Action.
         => Work put repeated multiple times

     - [x] (1-2 days) (#855) Delete data
         - There is no pay, but still consensus in Client-Handler and continue flow like put and mutation.
         - smaller.

     - [x] (3-5 days) (#858) Modify mutating Coin flows. These are all handled by the `ClientHandler`.
        - Modify Coin flows to go through parsec at the pay part of the flow. Transation goes through only after Parsec consensus (source Client-Handler)and then in 2.a the remaining flow proceed on all nodes (including destination client-handler).
          => Small number of flow (not just transfer), but different things for each
          => May require new action depending on continuation framework

     - [x] (2-3 days) (#857) CreateLoginPacketFor
        - Same as for mutating Coin flows.
        - Maybe the exact same code as mutating Coin.
         => Maybe some additonal action, combintion of login packet and coin flow (Depend on both these done.)

     - [x] (2-3 days) (#856) Create LoginPacket
        - Modify LoginPacket flows to go through parsec at the pay part of the flow. Transation goes through only after Parsec consensus (source Client-Handler) and then in 2.a & b the remaining flow proceed on all nodes (source client-handler).
        - Involve hooking up to allow restarting the flow when Parsec event consensus.
        - (Risk: call back or more simple way, once we solve that working. 1 week or more.)
         => Maybe good to do with Modify AuthKey InsAuthKey.
         => Same as mutation maybe need to go to different Action.
         => One of the simplest one.
         => Code has similar flow with an existing Action
            

     - [x] (1-2 days) (#870 ) Update LoginPacket
        - There is no pay, but still consensus in Client-Handler and continue flow to complete update.
          => Maybe go together with `AuthKey` `DelAuthKey`
          => A tiny bit different because no action, probably just need to send through Parsec, and do the full flow when it comes out.
          
     - [x] (1 day) (#862) Modify `AuthKey` `InsAuthKey`
         - Depend on Create LoginPacket done
         - Like Create LoginPacket

     - [x] (1 day) (#862) Modify `AuthKey` `DelAuthKey`
         - Depend on Update Login packet done
         - `DelAuthKey` paid in Phase 1, but need to change to be free.
          - There is no pay, but still consensus in Client-Handler and continue flow in Client-Handler.

    
- Running multiple Vaults in test setting (single process using mock routing and then mock_parsec and mock_quic_p2p) (8-14+ days).
    - [x] (2-3 days) (#853) run multiple vaults with mock_routing + simple test?
      - Need to make mock_routing work with multiple vault.
      - poll 5 vault as once (Maybe unkown.)
      - mock routing vote_for could not change. 
      - assumme client send same request to all vaults.
      - Environments to setup how many nodes.
    - [x] (3-4)(#876 ) run multiple vaults with mock_routing and only send request to some vaults 2/3?
      - Need to make mock_routing work with multiple vault.
      - mock routing vote_for could be a simple send first one to all vaults and filter other ones. (Alternative could use mock_parsec but maybe more complicated).
      - assumme client send same request to 2/3 vaults.
      - All vaults reply the same even if they did not get the requests.
    - [x] (1-2 days)(#876 ) Create some relevant tests that can run multiple vaults with mock_routing?
      - Maybe a subset of existing test modified to run with 1 vault or multiple vaults.
        => client in test don't care about number of vault so should be ok.
      - Assume all vaults reply the same (since we are testing good vaults.)
      - refunds + coin transfer + putting data + deleting data (3/4 tests)
    - [x] (2-5+ days) Make sure test can run with real routing with mock_parsec and mock_quick_p2p.
        - Need to make sure routing mock quic_p2p doing the right thing.
        - Need to build a working section (possibly the same as routing test by adding node successively, or maybe bringing them up together so it is simpler test?).

- [x] (#918) Running multiple Vaults in production (No mock)(1-5 days).
  - [x] (#918) (1-5 days, but risk to slip?) Run SCL test against mutliple vaults?
      - How do we set it up as a section? (Mutliple hard coded key probably.).
      - Dependent on SCL work.
      - Run each vaults in own process (Need to make sure that routing can initialize a section that can be used), Maybe they can just follow the normal process of first node and other node joing it. => Would need command line argument to setup first node + bootstrap info for other nodes.
       => Need hard coded contact of first node in quick-p2p.
      - SCL need to know all of the nodes: Combine connection infos together and use it for client.
      - Ignore vault dropping.

 Parsec vote vec<u8>or generic? (2.a issue implementation detail).
 Does payload goes into parsec. Design task? So maybe the simplest thing first does not loose to much work if we need to then fix performance with more complicated thing. (2.a issue)
 Nikita need answer if always 2/3 is good enough or if there are cases that needs different quorum.
> => Nikita: for Adults this might be a bit more tricky, but I think we should be good here for the phases 2.a & 2.b (esp. if  we don't need to pass e.g. ImmutableData GET requests through PARSEC).
> => JP what do you think would be tricky  for adults, do you have an example of something we could want to do?
=> JP: Could it be error handling needs quorum of 1?

**Comment by Lindsey17** [comment]
PR #867 covered issue #853, along with the consensus for the CreateBalance request and partially addressed some other requirements for the multi-vault testing environment (e.g.: running the existing test suite with multiple vaults).

**Comment by S-Coyle** [comment]
Closing legacy issues - parsec is no longer part of the network
