### ISSUE TITLE
Epic: Design flows Get/Put...

### ISSUE THREAD

**Issue by jeanphilippeD** [maidsafe/sn_node#843]
- Flow of I-data? (2a: 9 - 19 days (maybe less with overlap)) (2b: Unknown depend on finding a pattern)
  - Task:
  - [ ] Clarify existing flow (JP est: 1 day)
  - [ ] Design/Describe flow for phase 2a (JP est: 1-3 days)
  - [ ] Design/Describe flow for phase 2b (JP est: unknown, not all problem solved: 2 weeks?)
  - ~~Including `IDataHandler` (Elder) to `IDataHolder` (Adult/Elder) flow where the `IDataHandler` asks 3x `IDataHolder`s to store. For phase 2 these are 3 other Elders.~~
  - ~~Not sure in scope for phase 2. => No since all node have the data.~~
  - Put ~~and Get~~ go to every one, so do we need special communication from IDataHandle and IDataHolder or could they be the same.
  - Get can probably be handled by the one connected to client.
  - Client connection, connect to 1 or 3 for get whatever is easier.
- Flow of M-data?
  - Task:
  - [ ] Clarify existing flow (JP est: 1 day)
  - [ ] Design/Describe flow for phase 2a (JP est: 1-3 days)
  - [ ] Design/Describe flow for phase 2b (JP est: unknown, not all problem solved: 2 weeks?)
- Flow of A-data?
  - Task:
  - [ ] Clarify existing flow (JP est: 0.5 day assuming M-Data sorted)
  - [ ] Design/Describe flow for phase 2a (JP est: 1-3 days)
  - [ ] Design/Describe flow for phase 2b (JP est: 1-3 days assuming M-Data sorted)
- Flow for Put ?
  - Task:
  - [ ] Clarify existing flow (JP est: 0.5 day assuming M-Data sorted)
  - [ ] Design/Describe flow for phase 2a (JP est: 1-3 days)
  - [ ] Design/Describe flow for phase 2b (JP est: unknown, not all problem solved: 2 weeks?)
  => Even for 2a connect to all for put.
- Flow for Coin transfer?
  - Task:
  - [ ] Clarify existing flow (JP est: 1 day)
  - [ ] Design/Describe flow for phase 2a (JP est: 1-3 days)
  - [ ] Design/Describe flow for phase 2b (JP est: 1-3 days assuming Put sorted)

- [ ] Flow: Design and handle refund for most of the above flows properly (JP est: unknown, not all problem solved: 2-4 weeks?)?
    - Probably need to go through Parsec again, if different nodes get different errors?
    - PUT request failed need to refund client
    - PUT failed because of destination handler.
    - (2.a flow simpler 2b more complicated)
    - ...
        
~~^^ (Have a discussion for what we want with the flow)~~
=> Done: JP can drive the scope, essentially enough for people to know what we are doing in phase 2a, and 2b (can come later).

**Comment by maqi** [comment]
under the multi sections context

**Comment by S-Coyle** [comment]
Closing legacy issues
